config:
  replacements:
    - registry: quay.io
      repo_mappings:
        rhoai/odh-operator-bundle: rhoai/odh-operator-bundle
        rhoai/odh-rhel9-operator: rhoai/odh-rhel9-operator
        rhoai/odh-ml-pipelines-launcher-rhel9: rhoai/odh-ml-pipelines-launcher-rhel9
        rhoai/odh-ml-pipelines-driver-rhel9: rhoai/odh-ml-pipelines-driver-rhel9
        rhoai/odh-kuberay-operator-controller-rhel9: rhoai/odh-kuberay-operator-controller-rhel9
        rhoai/odh-kueue-controller-rhel9: rhoai/odh-kueue-controller-rhel9
        rhoai/odh-kf-notebook-controller-rhel9: rhoai/odh-kf-notebook-controller-rhel9
        rhoai/odh-data-science-pipelines-operator-controller-rhel9: rhoai/odh-data-science-pipelines-operator-controller-rhel9
        rhoai/odh-mm-rest-proxy-rhel9: rhoai/odh-mm-rest-proxy-rhel9
        rhoai/odh-model-controller-rhel9: rhoai/odh-model-controller-rhel9
        rhoai/odh-modelmesh-serving-controller-rhel9: rhoai/odh-modelmesh-serving-controller-rhel9
        rhoai/odh-codeflare-operator-rhel9: rhoai/odh-codeflare-operator-rhel9
        rhoai/odh-trustyai-service-operator-rhel9: rhoai/odh-trustyai-service-operator-rhel9
        rhoai/odh-training-operator-rhel9: rhoai/odh-training-operator-rhel9
        rhoai/odh-dashboard-rhel9: rhoai/odh-dashboard-rhel9
        rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel9: rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel9
        rhoai/odh-ml-pipelines-persistenceagent-v2-rhel9: rhoai/odh-ml-pipelines-persistenceagent-v2-rhel9
        rhoai/odh-data-science-pipelines-argo-argoexec-rhel9: rhoai/odh-data-science-pipelines-argo-argoexec-rhel9
        rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel9: rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel9
        rhoai/odh-ml-pipelines-runtime-generic-rhel9: rhoai/odh-ml-pipelines-runtime-generic-rhel9
        rhoai/odh-modelmesh-runtime-adapter-rhel9: rhoai/odh-modelmesh-runtime-adapter-rhel9
        rhoai/odh-notebook-controller-rhel9: rhoai/odh-notebook-controller-rhel9
        rhoai/odh-mlmd-grpc-server-rhel9: rhoai/odh-mlmd-grpc-server-rhel9
        rhoai/odh-ml-pipelines-api-server-v2-rhel9: rhoai/odh-ml-pipelines-api-server-v2-rhel9
        rhoai/odh-modelmesh-rhel9: rhoai/odh-modelmesh-rhel9
        rhoai/odh-trustyai-service-rhel9: rhoai/odh-trustyai-service-rhel9
        rhoai/odh-model-registry-operator-rhel9: rhoai/odh-model-registry-operator-rhel9
        rhoai/odh-model-registry-rhel9: rhoai/odh-model-registry-rhel9
        rhoai/odh-feast-operator-rhel9: rhoai/odh-feast-operator-rhel9
        rhoai/odh-feature-server-rhel9: rhoai/odh-feature-server-rhel9
  supported-ocp-versions:
    build:
      - name: v4.16
        base-image: registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.16
      - name: v4.17
        base-image: registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.17
      - name: v4.18
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.18
      - name: v4.19
        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.19
#      - name: v4.20
#        base-image: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9:v4.20
    release:
      - v4.16
      - v4.17
      - v4.18
      - v4.19
#      - v4.20
