config:
  supported-ocp-versions:
    - version: v4.14
      discontinued-from: rhods-operator.2.21.1
    - version: v4.15
      discontinued-from: rhods-operator.2.25.0
    - version: v4.16
      discontinued-from: rhods-operator.3.0.0
    - version: v4.17
      discontinued-from: rhods-operator.3.0.0
    - version: v4.18
      discontinued-from: rhods-operator.3.0.0
    - version: v4.19
    - version: v4.20
      onboarded-since: rhods-operator.2.25.0
