config:
  supported-ocp-versions:
    - version: v4.14
      discontinued-from: rhods-operator.2.21.1
    - version: v4.15
    - version: v4.16
    - version: v4.17
    - version: v4.18
    - version: v4.19
    - version: v4.20